import os
import sys
import numpy as np
import plotly.graph_objects as go

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from plotly.subplots import make_subplots
from dash import html, dcc, Input, Output, callback
from Isolation_Forest import IsolationForestAnomalyDetector

iTree_layout = [
    html.H1(
        "Recurssive Binary Partitions to Create Isolation Trees (iTree)",
        style={'textAlign': 'center', 'color': '#2b2d42'}
    ),

    html.P(
        "An isolated tree (iTree) is the binary tree generated by recurssive binary partitions "
        "on the data. This process is continued until either all data points are isolated, "
        "or a pre-determined tree limit is reached.",
        style={'textAlign': 'left', 'color': '#333'}
    ),

    html.Div([
        # Left Column (Code)
        html.Div([
            html.H3("Python Code"),
            dcc.Markdown(
                """
                ```python
                def iTree(self, X=None, counter=0, limit=100):

                    # fallback to use all data if X is None             
                    if X is None:
                        X = self.X

                    # base case: all points are isolated or height limit reached
                    if (len(X) <= 1) or (counter >= limit) or (np.all(X == X[0])):
                        # Create external node when point is isolated
                        return {'type': 'external', 'size': len(X)}

                    # Split left and right from random point on random axis
                    left_split, right_split, split_axis, split_point = self.binary_partition(X)

                    # Create internal node with recursive calls
                    return {
                        'type': 'internal',
                        'left': self.iTree(left_split, counter+1, limit),  # further split left into two, add 1 to the counter
                        'right': self.iTree(right_split, counter+1,limit), # further split right into two, add 1 to the counter
                        'split_axis': split_axis,
                        'split_point': split_point
                    }
                ```
                """
            )
        ], style={
            'flex': '1',
            'padding': '20px',
            'borderRight': '2px solid #ccc'
        }),

        # Right Column (Math)
        html.Div([
            html.H3("Mathematical Description"),
            dcc.Markdown(
                    r'''
                    Let $\mathbf{X} \in \mathbb{R}^{M \times d}$ denote the data matrix as previously defined.

                    Consider operation $\operatorname{iTree}(X, c, \ell)$
                    
                    **Stopping rule (external node).**
                    
                    If any of the following conditions hold:
                    $$
                      |\mathbf{X}| \le 1, \quad
                      c \ge \ell, \quad
                      \text{or all rows of } \mathbf{X} \text{ are identical},
                    $$
                    Then, recurssion is stopped.

                    **Recursive step (internal node).**

                    Else:
 
                    $$\operatorname{BinaryPartition}(S)$$
                    
                ''', mathjax=True
            ),
        ], style={
            'flex': '1',
            'padding': '20px'
        }),

    ], style={
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between'
    }),

    html.Div([
        html.H3(
            "Binary Partition Controls",
            style={
                'marginBottom': '10px',
                'fontWeight': 'bold',
                'color': '#2b2d42',
                'borderBottom': '2px solid #edf2f4',
                'paddingBottom': '8px'
            }
        ),

        html.Div([
            html.Div([
                html.Label(
                    "Number of Points:",
                    style={'fontWeight': '600', 'marginBottom': '6px', 'display': 'block'}
                ),
                dcc.Slider(
                    0, 520, 10,
                    value=20,
                    id='bp-number-of-points-slider',
                    marks={0: '0', 252: '252', 520: '520'},
                    tooltip={"always_visible": False},
                )
            ], style={'flex': '1', 'marginRight': '20px'}),

            html.Div([
                html.Button(
                    "Generate Random Split",
                    id='bp-generate-split-button',
                    n_clicks=0,
                    style={
                        'backgroundColor': '#2b2d42',
                        'color': 'white',
                        'border': 'none',
                        'borderRadius': '8px',
                        'padding': '10px 22px',
                        'cursor': 'pointer',
                        'fontWeight': 'bold',
                        'boxShadow': '2px 2px 5px rgba(0,0,0,0.15)',
                        'transition': '0.2s'
                    }
                )
            ], style={'display': 'flex', 'flexDirection': 'column', 'justifyContent': 'center'})
        ],
        style={
            'display': 'flex',
            'flexDirection': 'row',
            'alignItems': 'center',
            'padding': '15px',
            'backgroundColor': 'white',
            'borderRadius': '10px',
            'boxShadow': '0px 3px 8px rgba(0,0,0,0.07)',
            'border': '1px solid #edf2f4',
            'marginBottom': '20px'
        })
    ]),

    html.Div(
        [
            dcc.Graph(
                id='bp-scatter-plot',
                figure={},
                style={
                    'display': 'inline-block'
                }
            )
        ],
        style={
            'textAlign': 'center',
            'width': '100%'
        }
    ),

    html.Hr(),

    html.Div([
        dcc.Link(
            '← Go to Overview / Intro',
            href='/intro',
            style={
                'color': '#2b2d42',
                'fontSize': '18px',
                'textDecoration': 'none',
                'fontWeight': 'bold',
                'padding': '8px 14px',
                'border': '2px solid #2b2d42',
                'borderRadius': '8px',
                'backgroundColor': '#f8f9fa',
                'textAlign': 'center',
                'display': 'inline-block',
                'boxShadow': '2px 2px 4px rgba(0, 0, 0, 0.15)'
            }
        ),

        dcc.Link(
            'Go to iTrees →',
            href='/itrees',
            style={
                'color': '#2b2d42',
                'fontSize': '18px',
                'textDecoration': 'none',
                'fontWeight': 'bold',
                'padding': '8px 14px',
                'border': '2px solid #2b2d42',
                'borderRadius': '8px',
                'backgroundColor': '#f8f9fa',
                'textAlign': 'center',
                'display': 'inline-block',
                'boxShadow': '2px 2px 4px rgba(0, 0, 0, 0.15)'
            }
        ),

    ], style={
        'display': 'flex',
        'justifyContent': 'space-between',
        'padding': '20px 0'
    })
]
